import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideMenu } from "@/components/dashboard/side-menu";
import { MobileMenu } from "@/components/dashboard/mobile-menu";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideMenu />
        <MobileMenu />
        <main className="sm:ml-72 p-4">{children}</main>
      </body>
    </html>
  );
}
